version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - FRONTEND_URL=http://localhost:5173
      - DEV=False
      - SECRET_KEY=django-insecure-xn)s-mw1fhyq372a4l0^0y664n43_41b@+0p!rn6=e8+4shah+
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://localhost:8000
    volumes:
      - ./frontend:/app