version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      FRONTEND_URL: http://localhost:5173/
      DEV: "True"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:8000/
    volumes:
      - ./frontend:/app
      - node_modules_cached_frontend:/app/node_modules
  
volumes:
  node_modules_cached_frontend:
